"""
portfolio new <service-name>  — scaffold a new service from the golden path.

Generates a complete service directory with a Go HTTP service, Dockerfile,
Helm chart (with Argo Rollout + canary strategy), ArgoCD Application manifest,
and Backstage catalog entry — all pre-wired to the existing P1–P5 infrastructure.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path
from typing import Optional

import typer
from rich.console import Console
from rich.panel import Panel
from rich.tree import Tree

from portfolio.utils import config as cfg_module

app = typer.Typer()
console = Console()


def _snake(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")


# ─── Templates ────────────────────────────────────────────────────────────────

_MAIN_GO = '''package main

import (
\t"context"
\t"encoding/json"
\t"fmt"
\t"log/slog"
\t"net/http"
\t"os"
\t"os/signal"
\t"syscall"
\t"time"

\t"github.com/prometheus/client_golang/prometheus"
\t"github.com/prometheus/client_golang/prometheus/promauto"
\t"github.com/prometheus/client_golang/prometheus/promhttp"
)

var (
\tversion   = "dev"
\tbuildTime = "unknown"
)

var (
\thttpRequestsTotal = promauto.NewCounterVec(
\t\tprometheus.CounterOpts{{
\t\t\tName: "http_requests_total",
\t\t\tHelp: "Total HTTP requests by path and status code",
\t\t}},
\t\t[]string{{"method", "path", "status"}},
\t)
\thttpRequestDuration = promauto.NewHistogramVec(
\t\tprometheus.HistogramOpts{{
\t\t\tName:    "http_request_duration_seconds",
\t\t\tHelp:    "HTTP request duration in seconds",
\t\t\tBuckets: []float64{{0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1, 2, 5}},
\t\t}},
\t\t[]string{{"method", "path"}},
\t)
)

func getEnv(key, fallback string) string {{
\tif v := os.Getenv(key); v != "" {{
\t\treturn v
\t}}
\treturn fallback
}}

type responseWriter struct {{
\thttp.ResponseWriter
\tstatus int
}}

func (rw *responseWriter) WriteHeader(code int) {{
\trw.status = code
\trw.ResponseWriter.WriteHeader(code)
}}

func withMetrics(path string, next http.HandlerFunc) http.HandlerFunc {{
\treturn func(w http.ResponseWriter, r *http.Request) {{
\t\tstart := time.Now()
\t\trw := &responseWriter{{ResponseWriter: w, status: http.StatusOK}}
\t\tnext(rw, r)
\t\thttpRequestsTotal.WithLabelValues(r.Method, path, fmt.Sprintf("%d", rw.status)).Inc()
\t\thttpRequestDuration.WithLabelValues(r.Method, path).Observe(time.Since(start).Seconds())
\t}}
}}

func health(w http.ResponseWriter, r *http.Request) {{
\tw.Header().Set("Content-Type", "application/json")
\tjson.NewEncoder(w).Encode(map[string]string{{"status": "ok", "version": version}})
}}

func info(w http.ResponseWriter, r *http.Request) {{
\thostname, _ := os.Hostname()
\tw.Header().Set("Content-Type", "application/json")
\tjson.NewEncoder(w).Encode(map[string]string{{
\t\t"name": "{service_name}", "version": version, "hostname": hostname,
\t}})
}}

func main() {{
\tlog := slog.New(slog.NewJSONHandler(os.Stdout, nil))
\tport := getEnv("PORT", "{service_port}")

\tmux := http.NewServeMux()
\tmux.HandleFunc("/health", withMetrics("/health", health))
\tmux.HandleFunc("/", withMetrics("/", info))
\tmux.Handle("/metrics", promhttp.Handler())

\tsrv := &http.Server{{
\t\tAddr: ":" + port, Handler: mux,
\t\tReadTimeout: 10 * time.Second, WriteTimeout: 10 * time.Second,
\t}}

\tgo func() {{
\t\tlog.Info("starting", "service", "{service_name}", "port", port)
\t\tif err := srv.ListenAndServe(); err != nil && err != http.ErrServerClosed {{
\t\t\tlog.Error("server failed", "error", err); os.Exit(1)
\t\t}}
\t}}()

\tquit := make(chan os.Signal, 1)
\tsignal.Notify(quit, syscall.SIGTERM, syscall.SIGINT)
\t<-quit
\tlog.Info("shutting down")
\tctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
\tdefer cancel()
\tsrv.Shutdown(ctx)
}}
'''

_GO_MOD = '''module devops-portfolio/{service_name}

go 1.21

require (
\tgithub.com/prometheus/client_golang v1.19.0
)
'''

_DOCKERFILE = '''# syntax=docker/dockerfile:1
FROM golang:1.21-alpine AS builder
RUN apk add --no-cache ca-certificates tzdata git
WORKDIR /app
COPY go.mod ./
RUN go mod tidy && go mod download && go mod verify
COPY . .
ARG VERSION=dev
ARG BUILD_TIME=unknown
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \\
    go build \\
    -ldflags="-w -s -X main.version=${{VERSION}} -X \'main.buildTime=${{BUILD_TIME}}\'" \\
    -trimpath -o /server .

FROM gcr.io/distroless/static:nonroot
COPY --from=builder /server /server
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
USER nonroot:nonroot
EXPOSE {service_port}
ENTRYPOINT ["/server"]
'''

_CHART_YAML = '''apiVersion: v2
name: {service_name}
description: {service_name} — generated by portfolio new
type: application
version: 0.1.0
appVersion: "1.0.0"
'''

_VALUES_YAML = '''replicaCount: 2
image:
  repository: ""
  tag: "latest"
  pullPolicy: IfNotPresent
service:
  port: 80
  targetPort: {service_port}
ingress:
  enabled: false
rollout:
  revisionHistoryLimit: 3
  canary:
    steps:
      - setWeight: 20
      - pause:
          duration: 2m
      - analysis:
          templates:
            - templateName: success-rate
      - setWeight: 50
      - pause:
          duration: 2m
      - setWeight: 100
analysis:
  count: 5
  interval: 30s
  failureLimit: 1
  prometheusAddress: ""
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 65532
  fsGroup: 65532
  seccompProfile:
    type: RuntimeDefault
containerSecurityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop: [ALL]
livenessProbe:
  httpGet:
    path: /health
    port: {service_port}
  initialDelaySeconds: 10
  periodSeconds: 15
readinessProbe:
  httpGet:
    path: /health
    port: {service_port}
  initialDelaySeconds: 5
  periodSeconds: 10
'''

_ARGOCD_APP = '''apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {service_name}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: portfolio
  source:
    repoURL: https://github.com/{github_repo}.git
    targetRevision: HEAD
    path: {service_name}/helm/{service_name}
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: image.repository
          value: "{ecr_registry}/{ecr_image_prefix}/{service_name}"
        - name: image.tag
          value: "latest"
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    - group: networking.k8s.io
      kind: Ingress
      jsonPointers:
        - /metadata/annotations/alb.ingress.kubernetes.io~1actions.{service_name}-stable
'''

_CATALOG_INFO = '''apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: {service_name}
  description: {service_name} — generated from the DevOps portfolio golden path
  tags:
    - go
    - kubernetes
    - argo-rollouts
  annotations:
    github.com/project-slug: "{github_repo}"
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: user:burhaan
  system: devops-portfolio
  providesApis:
    - {service_name}-api
'''


@app.callback(invoke_without_command=True)
def new_service(
    name: str = typer.Argument(..., help="Service name (e.g. payment-service)"),
    port: int = typer.Option(8080, "--port", "-p", help="HTTP port the service listens on"),
    output_dir: Optional[Path] = typer.Option(None, "--output", "-o", help="Where to write the service (default: ./<name>)"),
    config_path: Optional[Path] = typer.Option(None, "--config", envvar="PORTFOLIO_CONFIG"),
) -> None:
    """
    Scaffold a new service from the portfolio golden path.

    Generates a complete service with a Go HTTP app, Dockerfile, Helm chart
    (Argo Rollout with canary), ArgoCD Application, and Backstage catalog entry.
    All security defaults from Projects 1–5 are baked in from the start.
    """
    cfg = cfg_module.load(config_path)
    service_name = _snake(name)
    dest = output_dir or (Path.cwd() / service_name)

    if dest.exists():
        console.print(f"[red]✗ Directory already exists: {dest}[/red]")
        raise typer.Exit(1)

    vars_ = {
        "service_name": service_name,
        "service_port": str(port),
        "github_repo":  cfg.github_repo or "GITHUB_USERNAME/devops-portfolio",
        "ecr_registry": cfg.ecr_registry or "ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com",
        "ecr_image_prefix": cfg.project,
    }

    files: dict[Path, str] = {
        dest / "app" / "main.go":                          _MAIN_GO.format(**vars_),
        dest / "app" / "go.mod":                           _GO_MOD.format(**vars_),
        dest / "app" / "Dockerfile":                       _DOCKERFILE.format(**vars_),
        dest / "helm" / service_name / "Chart.yaml":       _CHART_YAML.format(**vars_),
        dest / "helm" / service_name / "values.yaml":      _VALUES_YAML.format(**vars_),
        dest / "argocd" / f"{service_name}.yaml":          _ARGOCD_APP.format(**vars_),
        dest / "catalog-info.yaml":                        _CATALOG_INFO.format(**vars_),
    }

    for path, content in files.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)

    # Rich tree showing what was generated
    tree = Tree(f"[bold cyan]{service_name}/[/bold cyan]")
    app_branch = tree.add("[bold]app/[/bold]")
    app_branch.add("main.go        [dim]Go HTTP service with /health, /, /metrics[/dim]")
    app_branch.add("go.mod         [dim]Module with prometheus/client_golang[/dim]")
    app_branch.add("Dockerfile     [dim]Multi-stage distroless build[/dim]")
    helm_branch = tree.add(f"[bold]helm/{service_name}/[/bold]")
    helm_branch.add("Chart.yaml")
    helm_branch.add("values.yaml    [dim]Argo Rollout with canary strategy[/dim]")
    argocd_branch = tree.add("[bold]argocd/[/bold]")
    argocd_branch.add(f"{service_name}.yaml  [dim]ArgoCD Application (add to project-3-gitops/argocd/apps/)[/dim]")
    tree.add("catalog-info.yaml  [dim]Backstage Component registration[/dim]")

    console.print(Panel(tree, title=f"[green bold]✓ Generated {service_name}[/green bold]", border_style="green"))

    console.print("\n[bold]Next steps:[/bold]")
    console.print(f"  [cyan]1.[/cyan] Move [bold]{service_name}/[/bold] into your repo")
    console.print(f"  [cyan]2.[/cyan] Copy [bold]argocd/{service_name}.yaml[/bold] to [bold]project-3-gitops/argocd/apps/[/bold]")
    console.print(f"  [cyan]3.[/cyan] [dim]git add . && git commit && git push[/dim]")
    console.print(f"  [cyan]4.[/cyan] [dim]portfolio deploy image --tag sha-$(git rev-parse --short HEAD)[/dim]")
    console.print(f"  [cyan]5.[/cyan] [dim]portfolio deploy gitops --tag sha-$(git rev-parse --short HEAD)[/dim]")
    console.print()
